/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pxgepihdhvjetsylivmz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4Z2VwaWhkaHZqZXRzeWxpdm16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyOTE0MTAsImV4cCI6MjA4Nzg2NzQxMH0.Vtqe-97hZNwOaE-sBL-8P46fVo_-x6FtZqy7n6voVTU"